/** Mapeamento slug de categoria → macrocategoria (grupo da taxonomy.json). */
export const SLUG_TO_GROUP: Record<string, string> = {
  "romance-brasileiro": "Literatura Brasileira",
  "conto-brasileiro": "Literatura Brasileira",
  "poesia-brasileira": "Literatura Brasileira",
  "modernismo-brasileiro": "Literatura Brasileira",
  "regionalismo-brasileiro": "Literatura Brasileira",
  "literatura-do-nordeste": "Literatura Brasileira",
  "naturalismo-brasileiro": "Literatura Brasileira",
  "realismo-brasileiro": "Literatura Brasileira",
  "romantismo-brasileiro": "Literatura Brasileira",
  "literatura-gaucha": "Literatura Brasileira",
  "poesia-slam-e-marginal": "Literatura Brasileira",
  "romance-portugues": "Literatura Portuguesa",
  "poesia-portuguesa": "Literatura Portuguesa",
  "literatura-medieval-portuguesa": "Literatura Portuguesa",
  "modernismo-portugues": "Literatura Portuguesa",
  "neorrealismo-portugues": "Literatura Portuguesa",
  "renascimento-portugues": "Literatura Portuguesa",
  "epica-grega": "Literatura Clássica e Antiga",
  "tragedia-grega": "Literatura Clássica e Antiga",
  "comedia-grega": "Literatura Clássica e Antiga",
  "filosofia-classica": "Literatura Clássica e Antiga",
  "mitologia-classica": "Literatura Clássica e Antiga",
  "epica-latina": "Literatura Clássica e Antiga",
  "historia-antiga": "Literatura Clássica e Antiga",
  "romances-de-cavalaria": "Literatura Medieval e Renascentista",
  "literatura-arturiana": "Literatura Medieval e Renascentista",
  "literatura-italiana-renascentista": "Literatura Medieval e Renascentista",
  "soneto-renascentista": "Literatura Medieval e Renascentista",
  "poesia-provencal": "Literatura Medieval e Renascentista",
  "romance-ingles": "Literatura Anglo-Saxônica",
  "romance-americano": "Literatura Anglo-Saxônica",
  "conto-americano": "Literatura Anglo-Saxônica",
  "poesia-inglesa": "Literatura Anglo-Saxônica",
  "literatura-vitoriana": "Literatura Anglo-Saxônica",
  "literatura-modernista-inglesa": "Literatura Anglo-Saxônica",
  "beat-generation": "Literatura Anglo-Saxônica",
  "gotico-americano": "Literatura Anglo-Saxônica",
  "realismo-americano": "Literatura Anglo-Saxônica",
  "romance-frances": "Literatura Francesa",
  "poesia-francesa": "Literatura Francesa",
  "existencialismo-frances": "Literatura Francesa",
  "nouveau-roman": "Literatura Francesa",
  "iluminismo-frances": "Literatura Francesa",
  "simbolismo-frances": "Literatura Francesa",
  "naturalismo-frances": "Literatura Francesa",
  "romance-alemao": "Literatura Alemã e Austríaca",
  "romantismo-alemao": "Literatura Alemã e Austríaca",
  "expressionismo-alemao": "Literatura Alemã e Austríaca",
  "kafka-e-o-absurdo": "Literatura Alemã e Austríaca",
  "goethe-e-o-classicismo-alemao": "Literatura Alemã e Austríaca",
  "romance-russo": "Literatura Eslava e Russa",
  "realismo-russo": "Literatura Eslava e Russa",
  "dostoievski-e-o-existencialismo": "Literatura Eslava e Russa",
  "tolstoi-e-o-realismo-epico": "Literatura Eslava e Russa",
  "literatura-sovietica": "Literatura Eslava e Russa",
  "literatura-polonesa": "Literatura Eslava e Russa",
  "literatura-tcheca": "Literatura Eslava e Russa",
  "realismo-magico": "Literatura Latino-Americana",
  "boom-latino-americano": "Literatura Latino-Americana",
  "literatura-argentina": "Literatura Latino-Americana",
  "literatura-colombiana": "Literatura Latino-Americana",
  "literatura-mexicana": "Literatura Latino-Americana",
  "literatura-chilena": "Literatura Latino-Americana",
  "conto-latino-americano": "Literatura Latino-Americana",
  "literatura-japonesa": "Literatura Asiática e Oriental",
  "haiku-e-poesia-japonesa": "Literatura Asiática e Oriental",
  "literatura-chinesa-classica": "Literatura Asiática e Oriental",
  "literatura-indiana": "Literatura Asiática e Oriental",
  "literatura-arabe": "Literatura Asiática e Oriental",
  "literatura-persa": "Literatura Asiática e Oriental",
  "literatura-africana": "Literatura Asiática e Oriental",
  "ficcao-cientifica-classica": "Gêneros Ficcionais",
  "ficcao-cientifica-contemporanea": "Gêneros Ficcionais",
  "space-opera": "Gêneros Ficcionais",
  "cyberpunk": "Gêneros Ficcionais",
  "distopia": "Gêneros Ficcionais",
  "utopia": "Gêneros Ficcionais",
  "fantasia-epica": "Gêneros Ficcionais",
  "fantasia-urbana": "Gêneros Ficcionais",
  "horror-e-terror": "Gêneros Ficcionais",
  "suspense-psicologico": "Gêneros Ficcionais",
  "thriller": "Gêneros Ficcionais",
  "policial-classico": "Gêneros Ficcionais",
  "noir": "Gêneros Ficcionais",
  "romance-historico": "Gêneros Ficcionais",
  "ficcao-literaria": "Gêneros Ficcionais",
  "ficcao-experimental": "Gêneros Ficcionais",
  "filosofia-continental": "Não-Ficção Humanística",
  "filosofia-analitica": "Não-Ficção Humanística",
  "filosofia-oriental": "Não-Ficção Humanística",
  "etica-e-moral": "Não-Ficção Humanística",
  "politica-e-teoria-politica": "Não-Ficção Humanística",
  "historia-da-filosofia": "Não-Ficção Humanística",
  "epistemologia": "Não-Ficção Humanística",
  "logica-e-argumentacao": "Não-Ficção Humanística",
  "sociologia-e-antropologia": "Não-Ficção Humanística",
  "economia-e-pensamento-economico": "Não-Ficção Humanística",
  "fisica-e-cosmologia": "Ciências e Divulgação Científica",
  "biologia-e-evolucao": "Ciências e Divulgação Científica",
  "neurociencia": "Ciências e Divulgação Científica",
  "genetica": "Ciências e Divulgação Científica",
  "matematica-aplicada": "Ciências e Divulgação Científica",
  "inteligencia-artificial": "Ciências e Divulgação Científica",
  "tecnologia-e-sociedade": "Ciências e Divulgação Científica",
  "ecologia-e-meio-ambiente": "Ciências e Divulgação Científica",
  "historia-medieval": "História",
  "historia-moderna": "História",
  "historia-contemporanea": "História",
  "historia-do-brasil": "História",
  "historia-da-europa": "História",
  "historia-das-americas": "História",
  "historia-da-arte": "História",
  "historia-das-religioes": "História",
  "historia-da-ciencia": "História",
  "psicologia-clinica": "Psicologia e Comportamento",
  "psicanalise": "Psicologia e Comportamento",
  "psicologia-social": "Psicologia e Comportamento",
  "comportamento-humano": "Psicologia e Comportamento",
  "inteligencia-emocional": "Psicologia e Comportamento",
  "autoconhecimento": "Psicologia e Comportamento",
  "psicologia-cognitiva": "Psicologia e Comportamento",
  "neuropsicologia": "Psicologia e Comportamento",
  "estrategia-empresarial": "Negócios e Carreira",
  "lideranca": "Negócios e Carreira",
  "empreendedorismo": "Negócios e Carreira",
  "startups-e-inovacao": "Negócios e Carreira",
  "marketing": "Negócios e Carreira",
  "vendas-e-negociacao": "Negócios e Carreira",
  "gestao-e-administracao": "Negócios e Carreira",
  "financas-pessoais": "Negócios e Carreira",
  "investimentos": "Negócios e Carreira",
  "produtividade": "Negócios e Carreira",
  "carreira-e-desenvolvimento-profissional": "Negócios e Carreira",
  "habitos-e-disciplina": "Autodesenvolvimento",
  "mentalidade-e-mindset": "Autodesenvolvimento",
  "comunicacao-e-influencia": "Autodesenvolvimento",
  "relacionamentos": "Autodesenvolvimento",
  "estoicismo-pratico": "Autodesenvolvimento",
  "espiritualidade": "Autodesenvolvimento",
  "saude-e-bem-estar": "Autodesenvolvimento",
  "literatura-infantil": "Infantil e Juvenil",
  "literatura-juvenil": "Infantil e Juvenil",
  "young-adult": "Infantil e Juvenil",
  "fantasia-juvenil": "Infantil e Juvenil",
  "aventura-juvenil": "Infantil e Juvenil",
  "biografia-narrativa": "Biografia, Memória e Jornalismo",
  "autobiografia-e-memorias": "Biografia, Memória e Jornalismo",
  "memorias-e-diarios": "Biografia, Memória e Jornalismo",
  "jornalismo-literario": "Biografia, Memória e Jornalismo",
  "reportagem-literaria": "Biografia, Memória e Jornalismo",
  "biografia-romanceada": "Biografia, Memória e Jornalismo",
  "nao-ficcao-narrativa": "Biografia, Memória e Jornalismo",
  "teatro-classico": "Teatro e Dramaturgia",
  "teatro-moderno-e-contemporaneo": "Teatro e Dramaturgia",
  "teatro-epico": "Teatro e Dramaturgia",
  "teatro-experimental-e-absurdo": "Teatro e Dramaturgia",
  "teatro-politico-e-documental": "Teatro e Dramaturgia",
  "teoria-e-critica-teatral": "Teatro e Dramaturgia",
  "hq-e-graphic-novel": "Quadrinhos, HQ e Mangá",
  "manga": "Quadrinhos, HQ e Mangá",
  "quadrinho-autobiografico": "Quadrinhos, HQ e Mangá",
  "jornalismo-em-quadrinhos": "Quadrinhos, HQ e Mangá",
  "hq-brasileira": "Quadrinhos, HQ e Mangá",
  "contos-de-fada-e-fabulas": "Folclore e Literatura Popular",
  "folclore-brasileiro": "Folclore e Literatura Popular",
  "mitologia-e-lendas": "Folclore e Literatura Popular",
  "literatura-oral-e-popular": "Folclore e Literatura Popular",
  "true-crime": "Crime Real e Investigação",
  "criminologia-e-perfilamento": "Crime Real e Investigação",
  "investigacao-jornalistica": "Crime Real e Investigação",
  "casos-criminais-brasileiros": "Crime Real e Investigação",
};

/** Grupos na ordem de apresentação preferida. */
export const GRUPOS_ORDEM = [
  "Literatura Brasileira",
  "Literatura Portuguesa",
  "Literatura Anglo-Saxônica",
  "Literatura Francesa",
  "Literatura Alemã e Austríaca",
  "Literatura Eslava e Russa",
  "Literatura Latino-Americana",
  "Literatura Clássica e Antiga",
  "Literatura Medieval e Renascentista",
  "Literatura Asiática e Oriental",
  "Gêneros Ficcionais",
  "Não-Ficção Humanística",
  "História",
  "Ciências e Divulgação Científica",
  "Psicologia e Comportamento",
  "Negócios e Carreira",
  "Autodesenvolvimento",
  "Infantil e Juvenil",
  "Biografia, Memória e Jornalismo",
  "Teatro e Dramaturgia",
  "Quadrinhos, HQ e Mangá",
  "Folclore e Literatura Popular",
  "Crime Real e Investigação",
] as const;
